# Etapa 1 - Build
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# 🔥 Gera o Prisma Client
RUN npx prisma generate

RUN npm run build


# Etapa 2 - Produção
FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install --only=production

# Copia dist, node_modules e .prisma gerados no build
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/prisma ./prisma

EXPOSE 3000

CMD ["node", "dist/main"]
